<?php

namespace Tucompu\MantenimientoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MantenimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MantenimientoRepository extends EntityRepository
{
}
