tecnico:
    path:     /
    defaults: { _controller: "MantenimientoBundle:Tecnico:index" }

tecnico_show:
    path:     /{id}/show
    defaults: { _controller: "MantenimientoBundle:Tecnico:show" }

tecnico_new:
    path:     /new
    defaults: { _controller: "MantenimientoBundle:Tecnico:new" }

tecnico_create:
    path:     /create
    defaults: { _controller: "MantenimientoBundle:Tecnico:create" }
    requirements: { _method: post }

tecnico_edit:
    path:     /{id}/edit
    defaults: { _controller: "MantenimientoBundle:Tecnico:edit" }

tecnico_update:
    path:     /{id}/update
    defaults: { _controller: "MantenimientoBundle:Tecnico:update" }
    requirements: { _method: post|put }

tecnico_delete:
    path:     /{id}/delete
    defaults: { _controller: "MantenimientoBundle:Tecnico:delete" }
    requirements: { _method: post|delete }
