tipoequipo:
    path:     /
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:index" }

tipoequipo_show:
    path:     /{id}/show
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:show" }

tipoequipo_new:
    path:     /new
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:new" }

tipoequipo_create:
    path:     /create
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:create" }
    requirements: { _method: post }

tipoequipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:edit" }

tipoequipo_update:
    path:     /{id}/update
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:update" }
    requirements: { _method: post|put }

tipoequipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "MantenimientoBundle:TipoEquipo:delete" }
    requirements: { _method: post|delete }
